module.exports = {
    url: 'localhost:3000',
    elements: {
        version: '#versionNumber',
        queryBody: 'span[name="queryBody"]',
        error: 'li[class="errorMessage"]',
        saveBtn: '#saveBtn',
        menuButton: '.bm-burger-button',
        homeButton: 'p[name="homeOption"]',
        enterButton: 'a[href="#/enter"]',
        modifyButton: 'p[name="modifyOption"]',
        cancelButton: 'p[name="cancelOption"]',
        res: 'input[name="resInput"]',
        wid: 'input[name="widInput"]',
        hdr: 'input[name="hdrInput"]',
        mke: 'input[name="mkeInput"]',
        ori: 'input[name="oriInput"]',
        nam: 'input[name="namInput"]',
        sex: 'select[name="sexInput"]',
        rac: 'select[name="racInput"]',
        hai: 'input[name="haiInput"]',
        hgt: 'input[name="hgtInput"]',
        wgt: 'input[name="wgtInput"]',
        off: 'input[name="offInput"]',
        dow: 'input[name="dowInput"]',
        oln: 'input[name="olnInput"]',
        ols: 'input[name="olsInput"]',
        old: 'input[name="oldInput"]',
        lic: 'input[name="licInput"]',
        lis: 'input[name="lisInput"]',
        liy: 'input[name="lidInput"]',
        dat: 'input[name="datInput"]',
    }
}